//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebLibraryManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class book
    {
        public book()
        {
            this.checkouts = new HashSet<checkout>();
            this.circulations = new HashSet<circulation>();
        }
    
        public int Id { get; set; }
        public string code { get; set; }
        public string title { get; set; }
        public string author { get; set; }
        public string image { get; set; }
        public Nullable<System.DateTime> publish_date { get; set; }
        public string publish_place { get; set; }
        public string publisher { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<int> total { get; set; }
        public string create_by { get; set; }
        public Nullable<System.DateTime> create_date { get; set; }
        public string update_by { get; set; }
        public Nullable<System.DateTime> update_date { get; set; }
        public Nullable<int> active_fag { get; set; }
        public Nullable<int> material_type_id { get; set; }
    
        public virtual material_types material_types { get; set; }
        public virtual ICollection<checkout> checkouts { get; set; }
        public virtual ICollection<circulation> circulations { get; set; }
    }
}
