//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebLibraryManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class circulation
    {
        public int Id { get; set; }
        public Nullable<int> book_id { get; set; }
        public Nullable<int> patron_id { get; set; }
        public Nullable<bool> action { get; set; }
        public Nullable<System.DateTime> checkout_date { get; set; }
        public Nullable<System.DateTime> due_date { get; set; }
        public Nullable<System.DateTime> trans_date { get; set; }
        public Nullable<int> renew_count { get; set; }
        public string create_by { get; set; }
        public Nullable<System.DateTime> create_date { get; set; }
        public string update_by { get; set; }
        public Nullable<System.DateTime> update_date { get; set; }
        public Nullable<bool> active_fag { get; set; }
    
        public virtual book book { get; set; }
        public virtual patron patron { get; set; }
    }
}
