//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebLibraryManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class news
    {
        public int Id { get; set; }
        public string title { get; set; }
        public string summary { get; set; }
        public string body { get; set; }
        public Nullable<System.DateTime> publish_date { get; set; }
        public string image { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<int> total_view { get; set; }
        public Nullable<int> author_id { get; set; }
        public Nullable<int> category_id { get; set; }
        public string create_by { get; set; }
        public Nullable<System.DateTime> create_date { get; set; }
        public string update_by { get; set; }
        public Nullable<System.DateTime> update_date { get; set; }
        public Nullable<int> active_fag { get; set; }
    
        public virtual author author { get; set; }
        public virtual category category { get; set; }
    }
}
