//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebLibraryManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class patron
    {
        public patron()
        {
            this.blocked_tracking = new HashSet<blocked_tracking>();
            this.checkouts = new HashSet<checkout>();
            this.circulations = new HashSet<circulation>();
            this.renew_card_logs = new HashSet<renew_card_logs>();
        }
    
        public int Id { get; set; }
        public string code { get; set; }
        public Nullable<bool> status { get; set; }
        public string create_by { get; set; }
        public Nullable<System.DateTime> create_date { get; set; }
        public string update_by { get; set; }
        public Nullable<System.DateTime> update_date { get; set; }
        public Nullable<bool> active_fag { get; set; }
        public Nullable<int> type_id { get; set; }
        public Nullable<int> user_id { get; set; }
    
        public virtual ICollection<blocked_tracking> blocked_tracking { get; set; }
        public virtual ICollection<checkout> checkouts { get; set; }
        public virtual ICollection<circulation> circulations { get; set; }
        public virtual patron_type patron_type { get; set; }
        public virtual user_info user_info { get; set; }
        public virtual ICollection<renew_card_logs> renew_card_logs { get; set; }
    }
}
