//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebLibraryManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_info
    {
        public user_info()
        {
            this.patrons = new HashSet<patron>();
        }
    
        public int Id { get; set; }
        public string user_name { get; set; }
        public string password { get; set; }
        public string full_name { get; set; }
        public string email { get; set; }
        public string address { get; set; }
        public string phone { get; set; }
        public string code { get; set; }
        public Nullable<bool> name { get; set; }
        public Nullable<bool> order_number { get; set; }
        public Nullable<bool> status { get; set; }
        public Nullable<bool> role { get; set; }
        public string create_by { get; set; }
        public Nullable<System.DateTime> create_date { get; set; }
        public string update_by { get; set; }
        public Nullable<System.DateTime> update_date { get; set; }
        public Nullable<bool> active_fag { get; set; }
    
        public virtual ICollection<patron> patrons { get; set; }
    }
}
