//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebLibraryManagement.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WebLibraryManagementEntities : DbContext
    {
        public WebLibraryManagementEntities()
            : base("name=WebLibraryManagementEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<author> authors { get; set; }
        public DbSet<banner> banners { get; set; }
        public DbSet<blocked_tracking> blocked_tracking { get; set; }
        public DbSet<book> books { get; set; }
        public DbSet<category> categories { get; set; }
        public DbSet<checkout> checkouts { get; set; }
        public DbSet<circulation> circulations { get; set; }
        public DbSet<contact> contacts { get; set; }
        public DbSet<material_types> material_types { get; set; }
        public DbSet<news> news { get; set; }
        public DbSet<patron> patrons { get; set; }
        public DbSet<patron_type> patron_type { get; set; }
        public DbSet<renew_card_logs> renew_card_logs { get; set; }
        public DbSet<user_info> user_info { get; set; }
    }
}
